[proxy] impr: Addtional logging for cancellation queries
neondatabase/neon pull request #10039
Opened 2024-12-06 15:20 UTC by awarus

## Problem
Since cancellation tasks spawned in the background sometimes logs missing context. 
https://neondb.slack.com/archives/C060N3SEF9D/p1733427801527419?thread_ts=1733419882.560159&cid=C060N3SEF9D

## Summary of changes
Add `session_id` and change loglevel for cancellation queries

2024-12-06 15:29 UTC, conradludgate commented
Can we use [instrument()](https://docs.rs/tracing/latest/tracing/trait.Instrument.html#method.instrument) on the spawning step instead?

2024-12-06 15:32 UTC, cloneable submitted a review, later dismissed
I think we could really need an debug or info log at the beginning of the spawned cancel task and the task should also be instrumented and have a the session ID as span field. The span itself not have a parent span but can be marked as followed-from current span. Wdyt?

2024-12-09 09:51 UTC, awarus commented
@conradludgate @cloneable Thanks, made a change with Instrument, I didn't use it before :)

2024-12-09 10:57 UTC, awarus reviewed
Fixed

2024-12-09 11:45 UTC, conradludgate commented
I shall test this quickly to see what fields are in the cancel log

2024-12-09 17:30 UTC, cloneable requested changes
The `cancel_session` span is still attached to the `cancel_request` parent span. Since the task runs in the background it should be detached from the parent and be a root span and then the session ID is not redundant anymore.

2024-12-09 17:58 UTC, awarus commented
> The `cancel_session` span is still attached to the `cancel_request` parent span. Since the task runs in the background it should be detached from the parent and be a root span and then the session ID is not redundant anymore.

Sure, thought that follow-from relationship is necessary for the PR

2024-12-09 18:38 UTC, cloneable commented
> > The `cancel_session` span is still attached to the `cancel_request` parent span. Since the task runs in the background it should be detached from the parent and be a root span and then the session ID is not redundant anymore.
> 
> Sure, thought that follow-from relationship is necessary for the PR

Sorry for being confusing. Maybe what's shown in the log is not the parent span, but the follows-from span. I doubt that, but I'm actually not sure. Anyway, I meant that because the cancellation run asynchronously from the cancel request it should not be be part of the request's trace, it should start its own trace, but marked as related to the request's span. `info_span!` et al implicitly use the current span as the parent span and one has to explicitly set no parent or detach from parent.
We can choose to keep the separate task in the request's trace and remove the follows-from, or we remove the parent and keep follows-from. The latter is the technically correct thing to do here, but because the cancel task is short-lived it doesn't matter much. Once we enable tracing the request spans will be stretched out a little to cover both tasks.
That's all. Feel free to drop either the follows-from or the parent connection.

2024-12-10 09:28 UTC, cloneable approved these changes

2024-12-10 09:42 UTC, conradludgate commented
New sample:
```
2024-12-10T09:41:56.767107Z DEBUG accepted new TCP connection protocol="tcp" session_id=5337180c-08e3-4b78-94b8-41517d880f48
2024-12-10T09:41:56.767949Z DEBUG connect_request{protocol=tcp session_id=5337180c-08e3-4b78-94b8-41517d880f48 conn_info=127.0.0.1}: handling interactive connection from client protocol=tcp
2024-12-10T09:41:56.768222Z  INFO connect_request{protocol=tcp session_id=5337180c-08e3-4b78-94b8-41517d880f48 conn_info=127.0.0.1}:handshake: successful handshake session_type="cancellation"
2024-12-10T09:41:56.768966Z  INFO cancel_session{session_id=5337180c-08e3-4b78-94b8-41517d880f48}: cancelling query per user's request using key CancelKeyData(d9bc627d1887a549)
2024-12-10T09:41:56.769379Z DEBUG cancel_session{session_id=5337180c-08e3-4b78-94b8-41517d880f48}: query was cancelled
```

2024-12-10 10:15 UTC, merged

2024-12-10 10:25 UTC, cloneable commented
Ivan, sorry, a little late, but could you replace the drop() with an `.inspect_err( ... ).ok()` with a `tracing::debug!(error = err, "cancel_session failed")` and instrument the outer async block instead? Not urgent, but let's not silently ignore errors and at least have a debug log about it.