pageserver: revert flush backpressure (#8550)
neondatabase/neon pull request #10135
Opened 2024-12-13 09:29 UTC by erikgrinaker

## Problem

In #8550, we made the flush loop wait for uploads after every layer. This was to avoid unbounded buildup of uploads, and to reduce compaction debt. However, the approach has several problems:

* It prevents upload parallelism.
* It prevents flush and upload pipelining.
* It slows down ingestion even when there is no need to backpressure.
* It does not directly backpressure WAL ingestion (only via `disk_consistent_lsn`), and will build up in-memory layers.
* It does not directly backpressure based on compaction debt and read amplification.

An alternative solution to these problems is proposed in #8390. In the meanwhile, we revert the change to reduce the impact on ingest throughput.

## Summary of changes

Remove waiting on the upload queue in the flush loop.

This does reintroduce some risk of unbounded upload/compaction buildup. Until #8390, this can be addressed in other ways:

* Use `max_replication_apply_lag` (aka `remote_consistent_lsn`), which will more directly limit upload debt.
* Shard the tenant, which will spread the flush/upload work across more Pageservers and move the bottleneck to Safekeeper.

2024-12-13 11:47 UTC, arpad-m approved these changes
Fine by me but I want to see if Christian is okay with this (I think he is the one who originally suggested it)

2024-12-13 11:48 UTC, arpad-m requested changes
There is a few tests that fail, they need fixing.

2024-12-13 11:48 UTC, erikgrinaker commented
>There is a few tests that fail, they need fixing.

I know, working my way through them.

2024-12-13 14:09 UTC, arpad-m approved these changes

2024-12-13 15:25 UTC, erikgrinaker commented
In #10144, I add parallel layer uploads by only scheduling index uploads (which act as upload queue barriers) every 8 layers. 

If we want to derisk this, a halfway solution might be to keep the flush backpressure for now, but only trigger it every time we perform an index upload (every 8 layers) -- this would provide some parallelism and pipelining without building up an unbounded upload queue.

2024-12-13 15:49 UTC, problame approved these changes
Approving under the condition that this time we actually implement compact debt based backpressure.

Is this in Q1 planning?

I like your plan in https://github.com/neondatabase/neon/issues/10095

2024-12-15 09:45 UTC, erikgrinaker commented
Merging this to get some benchmark runtime.

>Is this in Q1 planning?

I took this to be part of "Write path throttling", which is right on the edge of Q1 inclusion. I agree that it's worth bumping this, certainly more so than S3 throttling. cc @jcsp

> I like your plan in #10095

Sharding complicates #10095 and can lead to deadlock. I have an updated proposal in #8390.

2024-12-15 09:47 UTC, merged