Add TLS support in scram-proxy
neondatabase/neon pull request #1643
Opened 2022-05-05 17:23 UTC by SergeyMelnikov

2022-05-05 17:31 UTC, kelvich approved these changes

2022-05-05 19:16 UTC, cicdteam requested changes

2022-05-05 19:16 UTC, cicdteam commented on .circleci/helm-values/staging.proxy-scram.yaml
>    authEndpoint: "http://console-staging.local:9095/management/api/v2"
by the way, this is wrong. AWS ALB do not serve 9095 port, it serve 80 (and pass traffic to port 9095 in target pods) only for internal console hostnames.

It should be simple `authEndpoint: "http://console-staging.local/management/api/v2"`

2022-05-05 20:04 UTC, cicdteam approved these changes

2022-05-05 20:48 UTC, merged

2022-05-06 06:47 UTC, hlinnaka commented
Cool!

I tried:

```
~$ psql postgres://hlinnaka%40zenith@start.stage.neon.tech/fragrant-rice-942513?sslmode=require
psql: error: connection to server at "start.stage.neon.tech" (35.169.157.111), port 5432 failed: server does not support SSL, but SSL was required
```

And:
```
~$ psql postgres://hlinnaka%40zenith@fragrant-rice-942513.cloud.stage.neon.tech/fragrant-rice-942513?sslmode=require
psql: error: connection to server at "fragrant-rice-942513.cloud.stage.neon.tech" (3.234.65.145), port 5432 failed: ERROR:  Internal error
```

There are more steps needed to have TLS working?

2022-05-06 08:00 UTC, SergeyMelnikov commented
In proxy logs for your attempt
```
got message: SslRequest
got message: StartupMessage { major_version: 3, minor_version: 0, params: {"application_name": "psql", "": "", "user": "hlinnaka@zenith", "database": "fragrant-rice-942513", "client_encoding": "UTF8"} }
cplane request: http://console-staging.local/management/api/v2/proxy_get_role_secret?cluster=fragrant-rice-942513&role=hlinnaka%40zenith
error: Bad authentication secret
```
Looks like something is wrong with communication back to console, cc @kelvich.

2022-05-06 09:57 UTC, kelvich commented
I've managed to connect to the cluster with scram+ssl. There is some bug about waking up compute in the new flow. You can try to create a new cluster, the click "generate _password_" and connect via `psql postgres://hlinnaka%40zenith:ASDFASDF@fragrant-rice-942513.cloud.stage.neon.tech/postgres`. Looking at this bug now.