Safekeeper: add timeline/tenant force delete HTTP endpoings
neondatabase/neon pull request #1653
Opened 2022-05-06 18:52 UTC by yeputons

This implements the basic version of #895.

* There is no auth in Safekeeper HTTP at all currently, so simply calling `check_permission` (like in Pageserver) is not enough.
* There are no checks of Safekeeper still working with the data, as "still working" is burry now: a timeline may be "active" while there are no compute nodes and all data is propagated.
* However, there is an attempt to report at least some information about "active" timelines (even if inaccurate) back to the caller. I'm not sure if it's information useful, but it's there just in case. Maybe for some metrics or whatnot.

2022-05-10 17:00 UTC, petuhovskiy requested changes

2022-05-11 10:41 UTC, arssher requested changes

2022-05-11 10:41 UTC, arssher commented on safekeeper/src/http/routes.rs
> +            "/v1/tenant/:tenant_id/timeline/:timeline_id/delete_force",
I'd drop `delete_force` part. It is strange to use delete method and repeat that in URL. And on force, currently we don't have a choice at all; if we have it later, we can specify in body the behaviour. Not very RESTy, but anyway.

I was also concerned about URL inconsistency with other methods, but that makes API closer to pageserver,  so ok, let's keep it this way and at some point make it fully identical.

2022-05-11 10:41 UTC, arssher commented on safekeeper/src/http/routes.rs
> +            "/v1/tenant/:tenant_id/delete_all_force",
same here

2022-05-11 10:41 UTC, arssher commented on libs/utils/src/http/request.rs
> +pub async fn ensure_no_body(request: &mut Request<Body>) -> Result<(), ApiError> {
do you have any tobacco?

2022-05-11 10:41 UTC, arssher commented on safekeeper/src/http/routes.rs
> +    let was_probably_active = GlobalTimelines::is_timeline_active(&zttid);
Right, we must delete map entry. Calling deactivate is also for now is useful.

2022-05-11 10:41 UTC, arssher commented on safekeeper/src/http/routes.rs
> +/// It does not try to stop any processing of the timeline; there is no such code at the time of writing.
Well, no. Timeline 'activeness' state machinery should be much better than it is now. We don't terminate walreceiver or walsender thread currently; basically the only (but important) purpose it currently serves is ensuring WAL commit_lsn reaches pageserver even if sync-safekeeper disconnects before that -- and then shut down callmemaybe.

2022-05-11 10:41 UTC, arssher commented on safekeeper/src/lib.rs
> +    pub fn tenant_no_timeline_dir(&self, tenant_id: &ZTenantId) -> PathBuf {
simply `tenant_dir`?

2022-05-12 18:35 UTC, yeputons commented
Rebasing...

2022-05-12 20:42 UTC, yeputons commented on safekeeper/src/http/routes.rs
> +    let was_probably_active = GlobalTimelines::is_timeline_active(&zttid);
Done it, but note that even a simple HTTP GET request can potentially add an item to the map by implicit creation. That requires that the state can be loaded from the disk, though.

2022-05-12 20:43 UTC, yeputons commented on safekeeper/src/http/routes.rs
> +/// 2. At the time of writing Safekeeper rarely marks a timeline inactive. E.g. disconnecting the compute node does nothing.
Still relevant: I do not delete the directory under mutex, and the old (de)activation logic is still in place.

2022-05-12 21:24 UTC, yeputons commented
Rebased, tests pass. I manually ensured that logs mention timeline deactivation, e.g. in test `test_delete_force`:

```
2022-05-12T21:15:34.151951Z  INFO {tid=15}:WAL acceptor{timeline=c8c39cbfe6876baf39b5ffae6b664223}: start receiving WAL since 0/16CD1B8
2022-05-12T21:15:34.165632Z  INFO {tid=17}: got query "IDENTIFY_SYSTEM"
2022-05-12T21:15:34.172847Z  INFO {tid=17}: got query "START_REPLICATION PHYSICAL 0/16CD1B8"
2022-05-12T21:15:34.173621Z  INFO {tid=17}:WAL sender{timeline=c8c39cbfe6876baf39b5ffae6b664223 pageserver_connstr=postgresql://no_user:@localhost:15000}: Start replication from 0/16CD1B8 till None
2022-05-12T21:15:34.938109Z  INFO {tid=15}:WAL acceptor{timeline=c8c39cbfe6876baf39b5ffae6b664223}: restart decoder from 0/0 to 0/16CD1B8
2022-05-12T21:15:35.145886Z  INFO deleting timeline 58d0f9b3b5154e1d8733dba1111fdde1-84fdb89cebf2caa5b6412134ee40f175
2022-05-12T21:15:35.146032Z  INFO timeline 84fdb89cebf2caa5b6412134ee40f175 is unsubscribed from callmemaybe to postgresql://no_user:@localhost:15000
2022-05-12T21:15:35.146289Z  INFO DELETE /v1/tenant/58d0f9b3b5154e1d8733dba1111fdde1/timeline/84fdb89cebf2caa5b6412134ee40f175 200 OK
2022-05-12T21:15:35.149809Z  INFO deleting timeline 58d0f9b3b5154e1d8733dba1111fdde1-84fdb89cebf2caa5b6412134ee40f175
2022-05-12T21:15:35.150074Z  INFO DELETE /v1/tenant/58d0f9b3b5154e1d8733dba1111fdde1/timeline/84fdb89cebf2caa5b6412134ee40f175 200 OK
2022-05-12T21:15:35.153847Z  INFO deleting timeline 58d0f9b3b5154e1d8733dba1111fdde1-d9a4f6bbf569d743cf83c9b3d45d9977
2022-05-12T21:15:35.158676Z  INFO DELETE /v1/tenant/58d0f9b3b5154e1d8733dba1111fdde1/timeline/d9a4f6bbf569d743cf83c9b3d45d9977 200 OK
2022-05-12T21:15:35.161881Z  INFO deleting timeline 58d0f9b3b5154e1d8733dba1111fdde1-00000000000000000000000000000000
2022-05-12T21:15:35.162059Z  INFO DELETE /v1/tenant/58d0f9b3b5154e1d8733dba1111fdde1/timeline/00000000000000000000000000000000 200 OK
2022-05-12T21:15:35.164292Z  INFO deleting all timelines for tenant 58d0f9b3b5154e1d8733dba1111fdde1
2022-05-12T21:15:35.164412Z  INFO timeline 7ffb084c773524c18fee3bbb3e7f8409 is unsubscribed from callmemaybe to postgresql://no_user:@localhost:15000
2022-05-12T21:15:35.168845Z  INFO DELETE /v1/tenant/58d0f9b3b5154e1d8733dba1111fdde1 200 OK
2022-05-12T21:15:35.172627Z  INFO deleting all timelines for tenant 58d0f9b3b5154e1d8733dba1111fdde1
2022-05-12T21:15:35.173583Z  INFO DELETE /v1/tenant/58d0f9b3b5154e1d8733dba1111fdde1 200 OK
2022-05-12T21:15:35.179149Z  INFO GET /v1/timeline/f76632e664b44c18b47c4b26d98f4fb1/c8c39cbfe6876baf39b5ffae6b664223 200 OK
2022-05-12T21:15:35.615155Z  INFO Got SIGQUIT. Terminating in immediate shutdown mode
```

2022-05-13 07:16 UTC, arssher approved these changes

2022-05-13 10:22 UTC, petuhovskiy approved these changes

2022-05-13 12:22 UTC, yeputons commented
Fixed typo in last commit's message, will push without squashing once tests are green once again.

2022-05-13 13:43 UTC, merged