Add a 5 minute timeout to python tests.
neondatabase/neon pull request #1704
Opened 2022-05-15 17:22 UTC by hlinnaka

The CI times out after 10 minutes of no output. It's annoying if a
test hangs and is killed by the CI timeout, because you don't get
information about which test was running. Try to avoid that, by adding
a slightly smaller timeout in pytest itself. You can override it on a
per-test basis if needed, but let's try to keep our tests shorter than
that.

2022-05-15 17:22 UTC, hlinnaka commented
Here's an example of a CI run that hit the 10 minute limit: https://app.circleci.com/pipelines/github/neondatabase/neon/6363/workflows/d8269b72-12bb-4e4c-b1b6-19b51f74facd/jobs/63770.

2022-05-15 18:09 UTC, yeputons requested changes
My two concerns:

1. Some times are timing out already.
2. Different timeout methods may be used depending on the system. The best is `signal`, as I understand, by it is UNIX-only (not an issue for us) and requires that our code never uses `SIGALRM` (not sure if it's the case). I'd also explicitly set this method in щгк configuration even though it's the current default if supported.

2022-05-15 19:03 UTC, hlinnaka commented
> My two concerns:
> 
> 1. Some times are timing out already.

Cool, that's exactly the kind of a flaky, hanging test I created this PR for :-)

> 2. Different timeout methods may be used depending on the system. The best is `signal`, as I understand, by it is UNIX-only (not an issue for us) and requires that our code never uses `SIGALRM` (not sure if it's the case). I'd also explicitly set this method in щгк configuration even though it's the current default if supported.

I think it's best to let the pytest-failure authors decide what the best method is, and stick to the default. I don't think we use SIGALRM in out python tests. I did use SIGALRM in the hack to get a flamegraph (commit a4700c9bbe), but that was in the pageserver process, not the pytest process, so I believe it's ok.

2022-05-15 19:38 UTC, hlinnaka commented
> > My two concerns:
> > 
> > 1. Some times are timing out already.
> 
> Cool, that's exactly the kind of a flaky, hanging test I created this PR for :-)

Turns out that was because of the issue with PR #1703 that I mentioned here: https://github.com/neondatabase/neon/pull/1703#issuecomment-1127007387 (I opened this PR on top of that one). This PR was very helpful in pinpointing that.

2022-05-16 07:42 UTC, hlinnaka commented
The `pg_regress-tests-debug` tests hit the 5 minute timeout on CI. I'll increase it for the `pg_regress` tests.

2022-05-16 09:40 UTC, LizardWizzard approved these changes
LGTM

2022-05-18 14:16 UTC, yeputons commented
> I think it's best to let the pytest-failure authors decide what the best method is

I wouldn't be so sure, they explicitly say "This is not the timeout you are looking for!" and write the following [in their README](https://pypi.org/project/pytest-timeout/)

> Please read this README carefully and only use this plugin if you understand the consequences.

I'm ok with leaving it as is.

@hlinnaka How about disabling/increasing timeout for benchmark tests and rebasing?

2022-05-18 23:33 UTC, yeputons approved these changes

2022-05-19 11:04 UTC, merged