Replace prefetch_reset with prefetch_in_progress in SMGR API
neondatabase/neon pull request #2635
Opened 2022-10-18 06:11 UTC by knizhnik

With large seqscan_prefetch_buffers, PrefetchBuffers becomes bottleneck, because it performed lookup of requested page in shared buffer hash. Time of Ketteq Q1 execution with all data loaded in shared buffers is increased from 10 seconds to 30 seconds with seqscan_prefetch_buffers=1000.

This PR prevents issuing new prefetch requests before all previous ones are proceeded.
Also prefetch is stopped once page is found in shared buffers. As a result, query execution time with war cache is not decreased if prefetch is enabled,

2022-10-18 15:44 UTC, hlinnaka approved these changes
Yes, this is better than before.

2022-10-18 18:30 UTC, knizhnik commented on pgxn/neon/pagestore_smgr.c
> + *	neon_prefetch_in_progress() -- reoe all previously rgistered prefeth requests
Fixed

2022-10-18 18:31 UTC, knizhnik commented
I need also approval for https://github.com/neondatabase/postgres/pull/218 
to be ale to merge this PR

2022-10-30 10:42 UTC, hlinnaka requested changes
You added a protocol change, with the new `prefetch` field, after my previous review. I'm not very happy with that. Firstly, it's a protocol change, so might cause trouble with older computes. It might happen to work, if there was padding previously in the place where the new field is added, but that's very subtle.

Secondly, I don't think the server should need a 'prefetch' flag like that. If it's a good idea to batch multiple responses together, can we check instead if there are more requests in the receive buffer that we could process?

2022-10-30 13:54 UTC, knizhnik commented
> You added a protocol change, with the new `prefetch` field, after my previous review. I'm not very happy with that. Firstly, it's a protocol change, so might cause trouble with older computes. It might happen to work, if there was padding previously in the place where the new field is added, but that's very subtle.
> 
> Secondly, I don't think the server should need a 'prefetch' flag like that. If it's a good idea to batch multiple responses together, can we check instead if there are more requests in the receive buffer that we could process?

I can undo this change. It has  questionable impact on performance. In some cases, for example for pg_prewarm, it offers up to two times  speed improvement with prefetch size = 1000. But for Q1 effect even slightly negative. It can be explained by the fact that pending responses reduce concurrency (because compute will receive response later and later can start processing of it,

Concerning delaying flush if we have something in input buffer, I have considered such approach  but 
- it suffers from the same problem as approach with `prefetch` flag
- it may require extra system call to check if some input is available (alternative is definitely to maintain own read buffer and check if it is not empty).
- read and write are preformed in different places and "linking" the, complicates the logic an make ode more obscure.

2022-10-30 19:47 UTC, knizhnik commented
Actually I realized that none of this schemas (my with `prefetch` flag or proposed by you - with checking for input) is safe.
The problem is that prefetch requst may be blocked in wait-for-lsn.
As far as response to the original page is not delivered, transaction is blocked. If two more transactions are blocked in this way, it can cause deadlock. 
I failed to create scenario of such deadlock with fine grain (per page) last written lsn cache. But with chunk-based last written lsn cache it is quite easy.

2022-10-30 20:50 UTC, hlinnaka approved these changes

2022-10-31 07:39 UTC, knizhnik commented
@hlinnaka  please notice that correspondent Postgres PR https://github.com/neondatabase/postgres/pull/218
is not yet approved, so I can merge this PR.

2022-11-07 19:18 UTC, hlinnaka commented
Is any of this still needed after https://github.com/neondatabase/neon/pull/2687?

2022-11-07 21:42 UTC, knizhnik commented
> Is any of this still needed after #2687?

Do you mean my last fixes with query cancelation?
If so, I don't know. Nobody asked me to review #2687
I will check but most likely tomorrow.
Because what I see now is that prefetch is not working. Or more precisely - it is working, because we are spending all time in prefetch_read. But instead of any speedup there is awful slowdown.
I am loading Ketteq database with main branch now. usually with enabled prefetch it takes about 10 minutes. And now after almost  2 hours it is still working, Creation of index take about 1000 seconds.

2022-11-07 22:22 UTC, knizhnik commented
I have used the same settings which I used in my setup which gives the best performance: seqscan_prefetch_buffers=1000
I have changed READ_BUFFER_SIZE to 1024.
Tomorrow I will check smaller value.
But in any case: maximal value of `seqscan_prefetch_buffer` is 1000, so it is possible to expect some reasonable behavior for this value.  Right now CPU usage is  < 0.5%,  no any disk activity... But it is not hanged. It is working but very slowly.

2022-11-08 05:28 UTC, knizhnik commented
Time of Q1 execution with `seqscan_prefetch_buffers=1000` is  161 seconds, with `seqscan_prefetch_buffers=100`  - 72 seconds. With original value of `READ_BUFFER_SIZE ` (128)  and  `seqscan_prefetch_buffers=100`  - 145 seconds.
So this is big step in backward direction:(

2022-11-08 06:42 UTC, knizhnik commented
Two good news: I can confirm that enabled prefetch is now causing degrade of performance with prewarmed shared buffers and that there are no problems with query cancellation.

2022-11-22 11:22 UTC, knizhnik commented
Alternative prefetch implementation was proposed by Mattias.

2022-11-22 11:22 UTC, closed without merging