Fix flaky tests
neondatabase/neon pull request #3616
Opened 2023-02-15 17:40 UTC by knizhnik

## Describe your changes

test_on_demand_download is flaky because not waiting until created image layer is transferred to S3.
test_tenants_with_remote_storage just leaves garbage at the end of overwritten file.

Right solution for test_on_demand_download is to add some API call to wait completion of synchronization with S3 (not just based on last record LSN). But right now it is solved using sleep.

## Issue ticket number and link

#3209 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

2023-02-16 08:08 UTC, koivunej approved these changes
It's a bit sad we cannot yet do better than sleep, but fixing the timetravel flakyness (#3209) is a good idea. Also the file truncation I missed.

Could you make the PR description useful, maybe mention `Fixes #3209` if that is fixed here?

2023-02-16 11:20 UTC, koivunej requested changes
Approval doesn't reset unless I request changes, see my earlier question about what is fixed by the sleep.

2023-02-16 16:18 UTC, knizhnik commented
> Approval doesn't reset unless I request changes, see my earlier question about what is fixed by the sleep.

Done.
Is it ok now?

2023-02-17 11:51 UTC, koivunej approved these changes
@knizhnik I think this only fixes the first part of timetravel flakyness... But it most likely gives it enough time for the second part (wait for flush lsn). Oki, approving.

2023-02-17 13:56 UTC, merged