Move tenant & timeline dir method to NeonPageserver and use them everywhere
neondatabase/neon pull request #5262
Opened 2023-09-08 18:45 UTC by rmodpur

## Problem
In many places in test code, paths are built manually from what NeonEnv.tenant_dir and NeonEnv.timeline_dir could do.

## Summary of changes
1. NeonEnv.tenant_dir and NeonEnv.timeline_dir moved under class NeonPageserver as the path they use is per-pageserver instance.
2. Used these everywhere to replace manual path building

#5258

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2023-09-13 04:30 UTC, rmodpur commented
@koivunej could you pls review this

2023-09-14 11:39 UTC, koivunej approved these changes
I think this is looking great! Thank you so much for working on this.

2023-09-14 11:49 UTC, jcsp approved these changes

2023-09-14 11:55 UTC, koivunej commented
Minor `approved-for-ci-run` issues, but hang tight...

2023-09-14 18:04 UTC, bayandin requested changes
Great work @rmodpur 👍 
Let's just lose these `None`s from methods calls and a couple of nitpicks

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_ondemand_download.py
> +    for layer in (env.pageserver.tenant_dir(None)).glob("*/timelines/*/*-*_*"):
```suggestion
    for layer in env.pageserver.tenant_dir(None).glob("*/timelines/*/*-*_*"):
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_ondemand_download.py
> +    for layer in (env.pageserver.tenant_dir(None)).glob("*/timelines/*/*-*_*"):
```suggestion
    for layer in env.pageserver.tenant_dir(None).glob("*/timelines/*/*-*_*"):
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_ondemand_download.py
> +    for layer in (env.pageserver.tenant_dir(None)).glob("*/timelines/*/*-*_*"):
```suggestion
    for layer in env.pageserver.tenant_dir(None).glob("*/timelines/*/*-*_*"):
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_tenant_detach.py
> +    assert (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_tenant_detach.py
> +    assert not (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert not env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_tenant_detach.py
> +    assert (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_tenant_detach.py
> +    assert not (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert not env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_tenant_detach.py
> +    assert (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_tenant_detach.py
> +    assert not (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert not env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-14 18:04 UTC, bayandin commented on test_runner/regress/test_walredo_not_left_behind_on_detach.py
> +    assert not (env.pageserver.tenant_dir(tenant_id)).exists()
```suggestion
    assert not env.pageserver.tenant_dir(tenant_id).exists()
```

2023-09-15 02:40 UTC, rmodpur commented on test_runner/fixtures/neon_fixtures.py
> +        return self.tenant_dir(tenant_id) / "timelines" / str(timeline_id)
I have pushed a new commit to address the comments

2023-09-15 10:15 UTC, bayandin approved these changes
Thanks again @rmodpur ❤️

2023-09-15 10:17 UTC, merged