metric: add started and killed walredo processes counter
neondatabase/neon pull request #5809
Opened 2023-11-07 07:15 UTC by rmodpur

In OOM situations, knowing exactly how many walredo processes there were at a time would help afterwards to understand why was pageserver OOM killed. Add `pageserver_wal_redo_process_total` metric to keep track of total wal redo process started, shutdown and killed since pageserver start.

Closes #5722

2023-11-07 07:16 UTC, rmodpur commented
@koivunej could you please review

2023-11-07 09:23 UTC, koivunej requested changes
I think this is looking good. Could I ask you to instead of a single counter_vec create a type hosting the 3 different counters and make that type the `pub(crate) static WAL_REDO_PROCESS_COUNTERS: Lazy<WalRedoProcessCounters> = ...`?

Rationale: walredo is very critical for us, and even though the contention from these counter accesses should always be low, it would allow us moving the strings ("started", "killed", "shutdown") to one place -- the `WalRedoProcessCounters::default` where they are created once and can be accessed by field after that.

2023-11-07 10:21 UTC, koivunej commented on pageserver/src/metrics.rs
> +    pub(crate) killed: GenericCounter<metrics::core::AtomicU64>,
```suggestion
    pub(crate) started: IntCounter,
    pub(crate) shutdown: IntCounter,
    pub(crate) killed: IntCounter,
```

2023-11-07 10:22 UTC, koivunej approved these changes
This is great! Thanks, could you look at the suggestion before I approve the CI run?

2023-11-07 10:31 UTC, rmodpur commented on pageserver/src/metrics.rs
> +    pub(crate) killed: GenericCounter<metrics::core::AtomicU64>,
done

2023-11-07 13:32 UTC, rmodpur commented
@koivunej sorry but had to fix a clippy lint

2023-11-07 15:38 UTC, koivunej commented
Zero worries, thanks for handling it!

2023-11-07 15:38 UTC, koivunej approved these changes
Aah it was the `|| ...())` suggestion, I should had caught that. It always bites me as well!

2023-11-08 10:53 UTC, problame requested changes
I'm not a fan of shoving the counters under the same metric.

Labels are supposed to add context / enricht the event.

But these labels are really different event types.

I'd argue for two separate counters:

* `..._starts` (no label)
* `..._stops` with label `cause` and values: `problem_during_launch` or `drop`

2023-11-08 11:07 UTC, koivunej commented
> I'm not a fan of shoving the counters under the same metric.
> 
> Labels are supposed to add context / enricht the event.
> 
> But these labels are really different event types.

@rmodpur please wait before making changes. The PR is now very close to as it was asked in the issue. The overall design of the metrics names and how to use them should be handled separatedly.

The PR is great work anyways, thanks, and we'll take it from here.

2023-11-09 20:22 UTC, problame approved these changes

2023-11-10 13:05 UTC, merged