failure during timeline creation: always clean up timeline dir
neondatabase/neon pull request #5914
Opened 2023-11-24 09:13 UTC by problame

Context: https://app.incident.io/neondb/incidents/103

Before this change, there's the following race condition if the tenant
gets deleted during timeline creation:

TBD, copy from https://neondb.slack.com/archives/C066ZFAJU85/p1700751858049319

The root of the problem is that we bail out of timeline creation without
cleaning up the uninit marker or timeline directory.

This PR changes the code to do that, and with our new policy for
infallible local IO, it also takes the opportunity to clean stuff up
around `TimelineUninitMark` & `UninitializedTimeline`.

I also added a missing fsync of the common parent directory between
timelines_dir removal and uninit marker removal.

We could probably get rid of the entire uninit mark idea, as
we no longer treat local FS state as the source of truth, and we only
upload to remote storage after successful creation (right?).

## Problem

## Summary of changes

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2023-11-24 09:33 UTC, koivunej requested changes
Some first ones; we don't need to use format! at all. I need to check the aborting paths, seems here are too many compared to likelyhood of logic bugs which are not infallible io. Also there's a lot of blocking IO.

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +            ));
```suggestion
            let uninit_mark_file_exists = self.uninit_mark_path.try_exists().fatal_err("stat() uninit mark file");
```

Span is already set. The file naming strategy we use is hard to see right away what file is causing trouble, but it is followable, so we don't need to include the paths.

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +            match fs::remove_dir_all(&self.timeline_path) {
Couldn't we rename this instead and then remove safely? The temp removing code is difficult to follow, but as long as the uninit mark exists we should be able to use even a static name.

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +                            on_fatal_io_error(&e, &format!("TimelineUninitMark::drop: remove_dir_all failed with NotFound, then remove_dir failed: {}", self.timeline_path));
```suggestion
                            on_fatal_io_error(&e, "remove_dir_all failed with NotFound, then remove_dir failed");
```

However I am not feeling great about all of these panics and aborts. We still have other tenants to serve. I don't think this situation is akin to EIO or some other error code telling us about filesystem corruption.

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +                        ),
```suggestion
                        "delete timeline directory",
```

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +            ));
```suggestion
            crashsafe::fsync(&self.common_parent).fatal_err("fsync after timeline dir removal");
```

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +            ));
```suggestion
            fs::remove_file(&self.common_parent).fatal_err("remove_file uninit mark");
```

2023-11-24 09:33 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +            ));
```suggestion
            crashsafe::fsync(&self.common_parent).fatal_err("fsync common parent dir");
```

2023-11-24 10:08 UTC, koivunej commented on pageserver/src/tenant/timeline/uninit.rs
> +                            on_fatal_io_error(&e, &format!("TimelineUninitMark::drop: remove_dir_all failed with NotFound, then remove_dir failed: {}", self.timeline_path));
Confirmed ``on_fatal_io_error` just aborts. It's not what we want to do unless the configuration is bad or there is filesystem corruption. Maybe it should be made more difficult to use.

2023-11-24 18:04 UTC, problame commented
Core idea obsoleted by #5917 , will re-open the leftover improvements of this PR in the near future, keeping it open until then.

2023-11-27 11:28 UTC, koivunej commented
Testing this with the reproducer, there seems to be an abort.

```
2023-11-27T11:27:14.913712Z ERROR request{method=POST path=/v1/tenant/9eb4626613b07f7cdb4796fdd968813f/timeline request_id=51bfde4c-c406-4ba9-898e-c1ffbf9a8253}:timeline_create{tenant_id=9eb4626613b07f7cdb4796fdd968813f shard=0000 timeline_id=4885b78a976c81c33a705fc488a916a6 lsn=None pg_version=Some(16)}:TimelineUninitMark_drop{timeline_path=/home/admin/src/neon/neon-main/test_output/test_long_timeline_create_then_tenant_delete[debug-pg16]/repo/pageserver_1/tenants/9eb4626613b07f7cdb4796fdd968813f/timelines/4885b78a976c81c33a705fc488a916a6}: Fatal I/O error: Is a directory (os error 21): TimelineUninitMark::drop: remove_file uninit mark: /home/admin/src/neon/neon-main/test_output/test_long_timeline_create_then_tenant_delete[debug-pg16]/repo/pageserver_1/tenants/9eb4626613b07f7cdb4796fdd968813f/timelines)
```

2024-04-12 09:46 UTC, problame commented
I have lost the context, and apparently this isn't a wide-spread issue. Abandoning.

2024-04-12 09:46 UTC, closed without merging