Add exponential backoff to page_server->send
neondatabase/neon pull request #6048
Opened 2023-12-05 23:17 UTC by save-buffer

## Problem
We currently spin and send a lot of stuff to hte pageserver if something goes wrong. Tracked in #6043 and #5757

## Summary of changes
Adds an exponential backoff to these connection attempts.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2023-12-06 10:08 UTC, knizhnik reviewed
I do not think that this two place is right place to add exponential backoff.
There are more places where reconnection can be performed in loop (for example `prefetch_wait_for`)

It seem to be more natural to move this logic to connect.

2023-12-07 07:21 UTC, koivunej approved these changes
This looks good to me assuming these loops have a way out with the connection being closed and are then retried at another level, for example if pageserver connectionstring is changed?

2023-12-07 20:37 UTC, jcsp commented on pgxn/neon/pagestore_smgr.c
> +#define INITIAL_EXPONENTIAL_BACKOFF_DELAY 1000
It's useful to name variables with a unit suffix when it's not obvious (I guess `_US` in these cases?)

2023-12-22 13:25 UTC, koivunej commented
I think this has now evolved to what @knizhnik was after, leaving the approval to them.

2023-12-22 13:31 UTC, jcsp commented
It seems like we still don't have a common understanding that exponential backoff is a good thing, but we need to get rid of the spinnning behavior ASAP.  @save-buffer can you update this PR's description to reflect what it does (current title is out of date).  We can keep the ticket open for implementing exponential backoff, but having some kind of delay between connection attempts is still better than nothing, so let's not hold this up.

2023-12-26 22:21 UTC, save-buffer commented
I think I've found a middle-ground. I don't think @knizhnik's issue was with exponential backoff per se, but with where in the code it was implemented. Implementing it inside of `pageserver_connect` does have advantages, and so he proposed a rate-limiting approach. I understand we'd want to do quick retries early on, so I've switched to an "exponential rate-limiting" approach, where if we retry our connection before the previous delay has elapsed, we double our delay. I _think_ this is a pretty elegant solution with the properties we want.

2023-12-27 10:04 UTC, knizhnik requested changes
I wonder why do we need reconnect interval smaller than 1 second?
Are there many cases when there is some short-time network outage (network blinking) and connection between compute and PS should be reestablished ASAP?

2023-12-27 16:55 UTC, save-buffer commented on pgxn/neon/libpagestore.c
> +#define MAX_RECONNECT_INTERVAL_USEC 100
I thoguht I'd tried to compile it... Fixed

2023-12-27 17:08 UTC, knizhnik approved these changes

2024-01-02 14:28 UTC, merged