Added missing PG_VERSION arg into compute node dockerfile
neondatabase/neon pull request #6382
Opened 2024-01-18 05:07 UTC by hamishc

## Problem

If you build the compute-node dockerfile with the PG_VERSION argument passed in (e.g. `docker build -f Dockerfile.compute-node --build-arg PG_VERSION=v15 .`, it fails, as the plv8-build stage doesn't have the PG_VERSION arg defined.

## Summary of changes

Added the PG_VERSION arg to the plv8-build stage of Dockerfile.compute-node

## Checklist before requesting a review

- [ x ] I have performed a self-review of my code.
- [ x ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2024-01-18 12:10 UTC, bayandin requested changes
Good catch @hamishc, thanks for the PR!

I've noticed that `neon-pg-ext-build` target also misses `PG_VERSION`; could you please add `ARG PG_VERSION ` there too?

2024-01-18 23:00 UTC, hamishc commented
> Good catch @hamishc, thanks for the PR!
> 
> I've noticed that `neon-pg-ext-build` target also misses `PG_VERSION`; could you please add `ARG PG_VERSION ` there too?

I've added it there, and I noticed it was missed in the `pg-embedding-pg-build` stage too.

2024-01-22 11:03 UTC, bayandin approved these changes

2024-01-22 11:05 UTC, merged

2024-01-22 11:06 UTC, bayandin commented
Merged! 
Thanks again for the help @hamishc ❤️