Show LFC statistic in EXPLAIN
neondatabase/neon pull request #6851
Opened 2024-02-21 08:46 UTC by knizhnik

## Problem

LFC has high impact on Neon application performance but there is no way for user to check efficiency of its usage

## Summary of changes

Show LFC statistic in EXPLAIN ANALYZE

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2024-02-21 08:55 UTC, Bodobolero reviewed
Should we have a test case for this?
The test could verify:
- that the code works fine in Vanilla postgres (does not display the LFC stats)
- that the code works fine in Neon (does show the LFC stats) - I can help write the E-2-E test for Neon once this PR is merged similar to this one https://github.com/neondatabase/cloud/blob/4bcd22bbfc8ecf2bef068d4c10ba699dd9caa496/tests_e2e/tests/sql/neon_pg_stat_statements.sql 
https://github.com/neondatabase/cloud/blob/16fcc8fd6f8ca88aa01930f3bb85fa8c7f4960c3/tests_e2e/tests/v2_public_api_tests/test_e2e_sql_regress.py

Should we have documentation input for our writers that describes the information displayed?

2024-02-26 14:07 UTC, lubennikovaav requested changes
I approved postgres PRs
and this one needs rebase to bump postgres versions.
please ping me, to approve this one, when it is ready.

2024-02-27 07:03 UTC, knizhnik commented
> I approved postgres PRs and this one needs rebase to bump postgres versions. please ping me, to approve this one, when it is ready.

Done

2024-02-27 12:33 UTC, lubennikovaav approved these changes

2024-02-27 12:45 UTC, merged

2024-02-29 13:23 UTC, Bodobolero commented
For test case see https://github.com/neondatabase/neon/pull/6968