tokio-epoll-uring: fallback to std-fs if not available & not explicitly requested
neondatabase/neon pull request #7120
Opened 2024-03-14 09:24 UTC by problame

fixes https://github.com/neondatabase/neon/issues/7116

Changes:

- refactor PageServerConfigBuilder: support not-set values
- implement runtime feature test
- use runtime feature test to determine `virtual_file_io_engine` if not explicitly configured in the config
- log the effective engine at startup

This needed a tiny bit of tokio-epoll-uring work, hence bumping it.
Changelog:

```
    git log --no-decorate --oneline --reverse 868d2c42b5d54ca82fead6e8f2f233b69a540d3e..342ddd197a060a8354e8f11f4d12994419fff939
    c7a74c6 Bump mio from 0.8.8 to 0.8.11
    4df3466 Bump mio from 0.8.8 to 0.8.11 (#47)
    342ddd1 lifecycle: expose `LaunchResult` enum (#49)
```

2024-03-14 09:39 UTC, jcsp approved these changes

2024-03-14 13:25 UTC, arpad-m requested changes
ok except typo

2024-03-14 13:25 UTC, arpad-m commented on pageserver/src/virtual_file/io_engine.rs
> +/// Somewhat costly under the hood, to only once.
```suggestion
/// Somewhat costly under the hood, do only once.
```

2024-03-14 14:03 UTC, skyzh approved these changes

2024-03-15 12:48 UTC, arpad-m commented
legit clippy failures:

```

  error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
     --> pageserver/src/virtual_file/io_engine.rs:272:1
      |
  272 | impl Into<IoEngineKind> for FeatureTestResult {
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = help: `impl From<Local> for Foreign` is allowed by the orphan rules, for more information see
              https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into
      = note: `-D clippy::from-over-into` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(clippy::from_over_into)]`
  help: replace the `Into` implementation with `From<virtual_file::io_engine::FeatureTestResult>`
      |
  272 ~ impl From<FeatureTestResult> for IoEngineKind {
  273 ~     fn from(val: FeatureTestResult) -> Self {
  274 ~         match val {
      |
  
  error: unneeded late initialization
     --> pageserver/src/virtual_file/io_engine.rs:305:17
      |
  305 |                 let remark;
      |                 ^^^^^^^^^^^
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_late_init
      = note: `-D clippy::needless-late-init` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(clippy::needless_late_init)]`
  help: declare `remark` here
      |
  306 |                 let remark = match e.raw_os_error() {
      |                 ++++++++++++
  help: remove the assignments from the `match` arms
      |
  308 ~                         "creating tokio-epoll-uring failed with non-OS error: {e}"
  309 |                     }
  310 |                     Some(nix::libc::EFAULT) => {
  311 ~                         "tokio-epoll-uring crate produces EFAULT?"
  312 |                     }
  313 |                     Some(nix::libc::EPERM) => {
  314 ~                         "creating io_uring fails with EPERM"
      |
  help: add a semicolon after the `match` expression
      |
  321 |                 };
      |                  +
```

2024-03-15 17:46 UTC, merged