Copy release images to prod ECR
neondatabase/neon pull request #8101
Opened 2024-06-18 18:06 UTC by SergeyMelnikov

## Problem
We want to have all released images in production ECR repository

## Summary of changes
Copy all docker images to production ECR repository

cc: https://github.com/neondatabase/cloud/issues/10177

2024-06-18 18:14 UTC, lassizci approved these changes

2024-06-18 18:14 UTC, bayandin requested changes

2024-06-18 18:14 UTC, bayandin commented on .github/workflows/build_and_test.yml
> +                                               369495373322.dkr.ecr.eu-central-1.amazonaws.com/neon:${{ needs.tag.outputs.build-tag }}
```suggestion
            docker buildx imagetools create -t 093970136003.dkr.ecr.eu-central-1.amazonaws.com/${image}:${{ needs.tag.outputs.build-tag }} \
                                               369495373322.dkr.ecr.eu-central-1.amazonaws.com/${image}:${{ needs.tag.outputs.build-tag }}
```

2024-06-18 18:24 UTC, bayandin reviewed
Apart from the missing `${image}` looks good!

An idea for testing:
- Replace `${{ needs.tag.outputs.build-tag }}` with `release-5733` in `promote-images` job
- Remove if-conditions from "Login to prod ECR" and "Copy all images to prod ECR"
- (don't forget to Revert these changes after the job has passed)

2024-06-19 08:50 UTC, bayandin approved these changes

2024-06-19 09:33 UTC, merged