Allow logical_replication_max_snap_files = -1
neondatabase/neon pull request #8702
Opened 2024-08-12 16:28 UTC by arssher

which disables the mechanism.

2024-08-12 16:32 UTC, jcsp approved these changes

2024-08-12 18:32 UTC, knizhnik requested changes

2024-08-12 18:32 UTC, knizhnik commented on pgxn/neon/neon.c
> +							300, -1, INT_MAX,
May be add explanation what -1 means (infinite number of files?)

2024-08-13 04:53 UTC, knizhnik approved these changes

2024-08-13 06:42 UTC, merged