Specialize WalIngest on PostgreSQL version
neondatabase/neon pull request #8904
Opened 2024-09-03 18:05 UTC by MMeent

The current code assumes that most of this functionality is version-independent, which is only true up to v16 - PostgreSQL 17 has a new field in CheckPoint that we need to keep track of.

This basically removes the file-level dependency on v14, and replaces it with switches that load the correct version dependencies where required.

## Problem

WalIngest hardcodes CheckPoint to one version's checkpoint. The layout hasn't changed between 14 and 16, but for PG17 it'll change, so we need this to be in place before the PG17 rollout.

## Summary of changes

Added new macros for automating generation of PG-versioned enums, and dispatching code based on those versioned enums; and make WalIngest use those macros for great benefits later.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2024-09-04 08:57 UTC, hlinnaka commented
Could a rust expert take a look at this, please? I have a feeling that it would be more idiomatic to make WalIngest generic over postgres version, or something like that. Not sure what exactly that should look like..

Other than that, the changes look good to me.

2024-09-04 15:53 UTC, problame reviewed
Instead of macros for enum dispatch, why not switch pg_version from `u32` to an `enum` and implement methods on that enum? 

I guess it increases the amount of code that would have to be written, and that code would look identical for pg14,15,16, and it wouldn't be all in one place at the use site, but scattered throughout the code base.

But, I fear that as soon as we start having actualy divergence between how different pg versions have to be handled, we'll start seeing the places that currently to macro dispatch become really ugly.

=> can you please stack a WIP branch on top of this one to show how the pg17 changes will look like? (I assume this PR is factored out of some WIP branch)

Maybe let the Rust style connoisseurs chime in @arpad-m @koivunej

---

The second thing: I'm a bit worried about the drive-by changes in this PR that increase precision of when we set `checkpoint_modified = true`.

Each time it's `true`, we put() a `Value::Image` record of the serialized checkpoint.

With the changes in this PR, we do it less often.

IIRC there was some need to have checkpoints created at a certain frequency for something in compute to not break. That PR is
* https://github.com/neondatabase/neon/pull/8484

but it still hasn't been merged.

For the record: I think all your drive-by fixes are correct, but, they constitute a change in behavior.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +enum_pgversion! {CheckpointVersion, pgv::CheckPoint}
CheckpointVersion seems like the wrong name. Why not simply call it `CheckPoint` ? We have module namespacing / qualified type syntax for a reason.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
>                      }
This check wasn't carried over.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +                        Merge::from(cp, &xlog_checkpoint);
This call and the `trait Merge` is a no-op in all cases. Why have it?

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +                    }
This is a drive-by change that makes the `checkpoint_modified` updating more precise than it was before.
Not wrong, just pointing it out and seeking confirmation.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +        });
If you look at it, the timestamp conversion is actually not versioned code.
We can avoid this dispatch here.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +            if cp.oldestXid != xlrec.oldest_xid || cp.oldestXidDB != xlrec.oldest_xid_db {
Similarly, a drive-by micro-optimization here.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +            });
This function also isn't postgres-versioned, so, we can avoid this dispatch.

2024-09-04 15:53 UTC, problame commented on pageserver/src/walingest.rs
> +        }
This is

1. drive-by micro-optimization to improve precision on checkpoint_modified
2. dispatching to code that is actually not postgres-versioned, so, we can avoid the dispatch.

2024-09-04 20:43 UTC, koivunej commented
Thanks for the ping. The macros generating many different types with versioned variants is an interesting choice, and not necessarily a bad one.

The code review finds by Christian however worry me (omissions, optimization), especially as I am not 100% if this even is a good idea. At minimum we should split those parts, have very refactoring or optimization.

2024-09-05 07:31 UTC, hlinnaka commented
Perhaps we should compile the whole file multiple times with the `for_all_postgres_versions` macro, to generate `walingest::v14:WalIngest`, `walingest::v15:WalIngest`, `walingest::v15:WalIngest`, `walingest::v16:WalIngest`, `walingest::v17:WalIngest`. There's already some code that's duplicated for each version, we could eliminate some of that I think.

BTW, while I'd like to find a nice solution here, this PR is OK to me as it is, too, and we should not let this block getting the v17 support done. This can be refactored later too.

2024-09-05 15:34 UTC, arpad-m submitted a review, later dismissed
I think this can also be handled via structs and traits, similar to the RemoteStorage trait and GenericRemoteStorage.

instead of a raw field access one would access a function that does the dispatch internally. one can still use macros but maybe just to generate these access functions.

2024-09-06 14:44 UTC, problame requested changes
Went over this together with @koivunej 

We finally understand why this change is needed for v17. Our understanding:

* The `CheckPoint` struct grew a new field `wal_level`
* Pageserver doesn't need to do anything special with the field `wal_level` (need not read or write it explicitly)
* But it needs to reproduce the it in the `pg_control` file of a basebackup
* v17 is the first occurence of us not being able to reuse the v14 type definitions for all versions

In that framework, the solution provided in this PR is valid and the least invasive.

So, in the interest of unblocking v17, I give my approval.

---

However, the approach _only_ works because

> * Pageserver doesn't need to do anything special with the field `wal_level` (need not read or write it explicitly)

Imagine if we _had_ to do special treatment, like here

```diff
     enum_pgversion_dispatch!(&mut self.checkpoint, CheckpointVersion, cp, {
                     if info == pg_constants::XLOG_NEXTOID {
                         let next_oid = buf.get_u32_le();
                         if cp.nextOid != next_oid {
                             cp.nextOid = next_oid;
                             self.checkpoint_modified = true;
                         }
                     } else if info == pg_constants::XLOG_CHECKPOINT_ONLINE
                         || info == pg_constants::XLOG_CHECKPOINT_SHUTDOWN
                     {
                         let mut checkpoint_bytes = [0u8; pgv::xlog_utils::SIZEOF_CHECKPOINT];
                         buf.copy_to_slice(&mut checkpoint_bytes);
                         let xlog_checkpoint = pgv::CheckPoint::decode(&checkpoint_bytes)?;
+                        if ...is_v17... {
+                             xlog_checkpoint.wal_level
+                        }
                         trace!(
```

It wouldn't compile.

So, we're just punting on the problem and on the way
* add non-idiomatic macros and
* at least on my setup, break rust-analyzer from finding usages

We need to prioritize a cleanup of this whole situation in Q4, cc @jcsp

---

Last, I request that you remove the drive-by optimizations and do them in a separate PR.
(I think I flagged all of them as review comments.)

In the meantime I found the issue regarding checkpoint frequency that I mentioned in my initial review comment:

* https://github.com/neondatabase/neon/pull/8484

Since that issue is still open, I don't know how high the severity is.
But anyway, let's keep the changes separate please.

2024-09-06 15:39 UTC, arpad-m commented
Thinking about it more, I don't think we should let perfect be the enemy of good. pgv17 support is an important deliverable, we can iterate on better designs later on (and I have multiple ideas on them).

2024-09-09 17:17 UTC, problame approved these changes
Approving, but please address the changes.
Please re-request review if non-trivial.

2024-09-09 17:17 UTC, problame commented on pageserver/src/walingest.rs
> +                    }
This is still doing the drive-by optimization, please undo it

2024-09-09 17:17 UTC, problame commented on pageserver/src/walingest.rs
> +            ))?;
This `max_of` + slicing business is needless micro-optimization.

Please move ZERO_CHECKPOINT into each `vXX` module and in the test just do `pgv::ZERO_CHECKPOINT`.

Also, do we have a test somewhere that checks that `pgv::CheckPoint` can deserialize the `pgv::ZERO_CHECKPOINT`?
If not please add one?

2024-09-09 22:01 UTC, merged