fix(pageserver): panic if fsync fails
neondatabase/neon pull request #9108
Opened 2024-09-23 16:20 UTC by skyzh

## Problem

close https://github.com/neondatabase/neon/issues/8140

The original issue is rather vague on what we should do. After discussion w/ @problame we decided to narrow down the problems we want to solve in that issue.

* read path -- do not panic for now.
* write path -- panic only on write errors (i.e., device error, fsync error), but not on no-space for now.

The guideline is that if the pageserver behavior could lead to violation of persistent constraints (i.e., return an operation as successful but not actually persisting things), we should panic. Fsync is the place where both of us agree that we should panic, because if fsync fails, the kernel will mark dirty pages as clean, and the next fsync will not necessarily return false. This would make the storage client assume the operation is successful.

## Summary of changes

Make fsync panic on fatal errors.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

2024-09-24 12:28 UTC, problame requested changes
Quick search for regex `\.sync_` in the codebase shows that this PR doesn't cover
- `VirtualFile::crashsafe_overwrite` 
- some usage of tokio::fs
  - https://github.com/neondatabase/neon/blob/a1323231bc65539f55eb1bfd341fb65d06d0ed22/pageserver/src/tenant/remote_timeline_client/download.rs#L185-L186
  - https://github.com/neondatabase/neon/blob/1708743e786cde41eb1bba51d4e5267895d8227d/pageserver/src/tenant/mgr.rs#L222
  - https://github.com/neondatabase/neon/blob/25a37215f35896eedfbdc0e0f52857619357317a/pageserver/src/consumption_metrics/disk_cache.rs#L104

Also, there's the question how to avoid regressing the code base in the future. Can we use clippy to ban `tokio::fs::File::sync_all` ?

2024-09-24 18:04 UTC, skyzh commented
> Also, there's the question how to avoid regressing the code base in the future. Can we use clippy to ban tokio::fs::File::sync_all ?

We still have usage of fsync in safekeeper, and I don't plan to fix them in this pull request for now, so we cannot enforce the clippy lint until we fix all occurrences :(

2024-09-26 15:35 UTC, problame approved these changes

2024-09-26 18:21 UTC, skyzh commented
created https://github.com/neondatabase/neon/issues/9172 for safekeeper

2024-09-27 18:58 UTC, merged