Add compute metric for gathering the backpressure throttling time
neondatabase/neon pull request #9176
Opened 2024-09-26 20:57 UTC by tristan957

2024-09-26 20:58 UTC, tristan957 commented
Do we have any documentation about what this metric actually means? Is it something like the time a compute has spent sleeping instead of shipping WAL to the safekeepers or something?

2024-09-27 16:03 UTC, hlinnaka approved these changes

2024-09-27 16:05 UTC, hlinnaka commented
> Do we have any documentation about what this metric actually means?

I don't think we do

> Is it something like the time a compute has spent sleeping instead of shipping WAL to the safekeepers or something?

It's the time the compute has spent in total sleeping in the throttling code, to prevent it from producing WAL so fast that the safekeepers/pageserver cannot keep up digesting it.

2024-09-27 17:55 UTC, petuhovskiy requested changes

2024-09-27 17:55 UTC, petuhovskiy commented on compute/etc/neon_collector.yml
> +    SELECT backpressure_throttling_time() AS throttled;
```suggestion
    SELECT neon.backpressure_throttling_time() AS throttled;
```

2024-09-27 18:14 UTC, tristan957 commented
After https://github.com/neondatabase/neon/pull/9184 is merged, I'll rebase this and fix Arthur's comment.

2024-10-30 14:23 UTC, ololobus approved these changes

2024-10-30 14:56 UTC, petuhovskiy approved these changes

2024-10-30 14:58 UTC, merged