[local_proxy] update api for pg_session_jwt
neondatabase/neon pull request #9359
Opened 2024-10-11 12:55 UTC by conradludgate

pg_session_jwt now:
1. Sets the JWK in a PGU_BACKEND session guc, no longer in the init() function.
2. JWK no longer needs the kid.

2024-10-11 12:55 UTC, conradludgate commented on proxy/src/serverless/local_conn_pool.rs
> +fn sign_jwt(sk: &SigningKey, payload: &[u8]) -> String {
I had a bit of time so I thought I'd try make this work with a single alloc only :)

2024-10-14 15:15 UTC, conradludgate commented on proxy/src/serverless/backend.rs
> +            if let Err(e) = client.query("select auth.init();", &[]).await {
it is not necessary. in fact this query() block can only accept a single query due to the way the postgres protocol works!

2024-10-14 15:16 UTC, conradludgate commented on proxy/src/serverless/backend.rs
> +            .options(&format!("-c pg_session_jwt.jwk={jwk}"));
yeah it's weird :/ I've tested it and the `-c` is necessary. So strange.

2024-10-14 15:17 UTC, conradludgate commented on proxy/src/serverless/backend.rs
> +            debug!(?pid, "setting up backend session state");
not necessary. can probably remove it. `kid=pid` and I just updated it to match.

2024-10-14 15:18 UTC, conradludgate commented on proxy/src/serverless/local_conn_pool.rs
> +fn sign_jwt(sk: &SigningKey, payload: &[u8]) -> String {
Yeah, probably should do that 😅

2024-10-14 15:22 UTC, conradludgate commented on proxy/src/serverless/local_conn_pool.rs
> +        assert_eq!(jwt, "e30.eyJmb28iOiJiYXIiLCJqdGkiOjIsIm5lc3RlZCI6eyJqdGkiOiAidHJpY2t5IG5lc3RpbmcifX0.qZnHxDfNigd7eegbHtcjK-l3Gv-zQtx6-6x-uP1IBfwS4Z4Jepc3T3RfRaIbPpWOjeVBrhLjB3jir5_LtSVPXQ");
As for how I validated the test, I copied the token into <https://jwt.io/> and manually validated that the token met my expectations

2024-10-14 16:03 UTC, cloneable commented on proxy/src/serverless/local_conn_pool.rs
> +        assert_eq!(jwt, "e30.eyJmb28iOiJiYXIiLCJqdGkiOjIsIm5lc3RlZCI6eyJqdGkiOiAidHJpY2t5IG5lc3RpbmcifX0.qZnHxDfNigd7eegbHtcjK-l3Gv-zQtx6-6x-uP1IBfwS4Z4Jepc3T3RfRaIbPpWOjeVBrhLjB3jir5_LtSVPXQ");
I tried exactly that, but couldn't figure out how to use the 32 0x01s for signing. Would be good to have at least a little comment describing this. Was hoping for a cli tool command one could run, but linking to jwt.io is okay, too.

2024-10-15 07:58 UTC, mrl5 requested changes

2024-10-15 07:58 UTC, mrl5 commented on compute/Dockerfile.compute-node
> +    wget https://github.com/neondatabase/pg_session_jwt/archive/b30d7df196d0cb816365e565a7579f9c78221206.tar.gz -O pg_session_jwt.tar.gz && \
one more fix was needed, please change commit hash to `5aee2625af38213650e1a07ae038fdc427250ee4`

2024-10-15 07:58 UTC, mrl5 commented on compute/Dockerfile.compute-node
> +    echo "ea9a666af4bcdd84e8363f56d0b730849bfcc94db4f01713d579859a46435818 pg_session_jwt.tar.gz" | sha256sum --check && \
one more fix was needed, please update sha256sum accordingly
(on my end it's `5d91b10bc1347d36cffc456cb87bec25047935d6503dc652ca046f04760828e7` now)

2024-10-15 10:09 UTC, mrl5 approved these changes

2024-10-15 10:09 UTC, conradludgate commented on proxy/src/serverless/local_conn_pool.rs
> +        assert_eq!(jwt, "e30.eyJmb28iOiJiYXIiLCJqdGkiOjIsIm5lc3RlZCI6eyJqdGkiOiAidHJpY2t5IG5lc3RpbmcifX0.qZnHxDfNigd7eegbHtcjK-l3Gv-zQtx6-6x-uP1IBfwS4Z4Jepc3T3RfRaIbPpWOjeVBrhLjB3jir5_LtSVPXQ");
Updated. Can you test the process?

2024-10-15 10:39 UTC, cloneable approved these changes

2024-10-15 10:41 UTC, cloneable commented on proxy/src/serverless/local_conn_pool.rs
> +        assert_eq!(jwt, "e30.eyJmb28iOiJiYXIiLCJqdGkiOjIsIm5lc3RlZCI6eyJqdGkiOiAidHJpY2t5IG5lc3RpbmcifX0.qZnHxDfNigd7eegbHtcjK-l3Gv-zQtx6-6x-uP1IBfwS4Z4Jepc3T3RfRaIbPpWOjeVBrhLjB3jir5_LtSVPXQ");
Yes, works! I guess going from the 32 0x01 signing key seed to a key is impl specific and can't be tested easily externally.

2024-10-15 12:13 UTC, merged